# Generated by Django 3.0.2 on 2020-02-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haircut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('heading', models.CharField(max_length=255)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceHead', models.CharField(max_length=255)),
                ('servicesDetail', models.TextField()),
            ],
        ),
    ]
