# Generated by Django 3.0.2 on 2020-02-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduleA7', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Haircut',
        ),
    ]
