# Generated by Django 3.0.2 on 2020-02-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleA7', '0003_delete_haircut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haircut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('heading', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
