# Generated by Django 3.0.2 on 2020-02-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleA7', '0004_haircut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('haircut', models.CharField(max_length=255)),
            ],
        ),
    ]
